### ISSUE TITLE
Switch from mongoose to something else

### ISSUE THREAD

**Issue by swlkr** [joy-framework/joy#12]
Just like the title says switch to h2o from mongoose for the MIT license

https://powerdns.org/libh2o/#hello,andwelcometolibh2o

related to #5 

This should probably be a separate project, similar to [circlet](https://github.com/janet-lang/circlet)

**Comment by swlkr** [comment]
I also noticed a few other ones that were MIT/ISC licensed:

- https://github.com/fredrikwidlund/libreactor
- https://github.com/boazsegev/facil.io
- https://github.com/jorisvink/kore

kore and libreactor seem the easiest, I'm leaning towards libreactor more even though the docs don't really exist yet

**Comment by sepisoad** [comment]
just to make the situation worse I add another option:

https://babelouest.github.io/ulfius/

**Comment by sepisoad** [comment]
And unlike the first 3 libraries, I think `ulfius` works on all major OSes,

**Comment by swlkr** [comment]
Hm, that one isn’t MIT though

**Comment by swlkr** [comment]
There’s also this [one](https://github.com/lammertb/libhttp) which is an MIT licensed spiritual successor to mongoose and https://github.com/civetweb/civetweb

**Comment by sepisoad** [comment]
i think this one fit better

**Comment by swlkr** [comment]
I couldn't get `libHTTP` to work at all, so I fell back to `civetweb` and that seemed to work pretty well. Here's the resulting library: https://github.com/joy-framework/halo

I stuck with the ring/circlet theme and *combined* it with the Janet theme and went with halo.

They don't have halos in the good place, but it's the best I could do 😅

**Comment by swlkr** [comment]
I’ve been working on this for a while and I finally hit on something that works reasonably well. It does most of the same things circlet does and it’s MIT licensed. It’s a combination of three things

- https://github.com/antirez/sds for strings
- https://github.com/rxi/sandbird for socket/http stuff
- https://github.com/nodejs/http-parser for http header/body parsing

sds is BSD-2 licensed but it seems compatible with MIT. If it isn’t I can drop it fairly easily.

**Comment by swlkr** [comment]
Closed by fb2791e115faaec727a19f59d96baf182bd7e1eb
