### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by swlkr** [joy-framework/joy#16]
- [x] push live
- [x] open source
- [ ] add tutorial video
- [x] ~~make video better~~
- [x] let's encrypt ssl

**Comment by swlkr** [comment]
Figured I'd show what it looks like as I'm working on it

<img width="838" alt="Screen Shot 2019-12-12 at 9 51 17 AM" src="https://user-images.githubusercontent.com/159336/70732069-066a8280-1cc5-11ea-8c34-8508d5ecec30.png">

**Comment by swlkr** [comment]
Desktop
<img width="1680" alt="Screen Shot 2019-12-14 at 5 11 42 PM" src="https://user-images.githubusercontent.com/159336/70856216-d671d980-1e94-11ea-87be-9cd7ad6797fb.png">

Mobile
![localhost_8080_(iPhone X)](https://user-images.githubusercontent.com/159336/70856253-7cbddf00-1e95-11ea-9984-993d5e2b73c3.png)

**Comment by swlkr** [comment]
this might be live depending on your dns settings.

the video still needs a little work (i.e. me talking and giving a little intro tutorial), but i pushed it live anyway.

**Comment by sepisoad** [comment]
is the code section intentionally styled to not show parenthesis?

**Comment by swlkr** [comment]
No it shows them, they're just really hard to see, still tweaking
