### ISSUE TITLE
Link Rendering Problem

### ISSUE THREAD

**Issue by javan-z** [joy-framework/joy#36]
`[:p  "Powered by"
              [:a {:href "https://www.w3schools.com/w3css/default.asp" 
                :title "W3.CSS" :target "_blank" 
          	:class "w3-hover-text-blue"} "W3.CSS"]]`

This code doesn't create: Powered by W3.CSS <-- with the last part as a link
Only output is : Powered by
link is blank
What am I doing wrong here?
and What is poolparty?
Enjoying the framework Thanks!

**Comment by swlkr** [comment]
Yeah, it's kind of annoying, not 1:1 with hiccup quite yet, but there is a way around it by wrapping strings with span like this:

```clojure
[:p 
  [:span "Powered by "]
  [:a {:href "https://www.w3schools.com/w3css/default.asp"
         :title "W3.CSS"
         :target "_blank"
         :class "w3-hover-text-blue"} 
      "W3.CSS"]]
```

**Comment by swlkr** [comment]
Oh and poolparty is a threaded go webserver that should work with joy, if you want a faster server than the default.

**Comment by javan-z** [comment]
I'm checking out poolparty.  Thanks the span works perfect!
