### ISSUE TITLE
where is the path after jpm in Mac?

### ISSUE THREAD

**Issue by kwccoin** [joy-framework/joy#43]
Just not sure.  Usually there is some remark where should I get my path but not the script here?

**Comment by swlkr** [comment]
I think by default it’s `/usr/local/lib/janet`

but you can check with `(dyn :syspath)` in the repl

**Comment by kwccoin** [comment]
Thanks. Sorted. In /usr/local/lib/janet/bin; wonder why not in /usr/local/bin/ like janet

TL; DR

---------

The (dan :syspath) return "/usr/local/Cellar/janet/1.8.1/lib/janet"; not sure

I tried /usr/local/lib/janet and found there is a bin there

Hence, "/usr/local/lib/janet/bin" is ok with

export PATH=$PATH:/usr/local/lib/janet/bin

which joy give you /usr/local/lib/janet/bin/joy which is differ from /usr/local/bin/janet

Why it is not there?

**Comment by kwccoin** [comment]
Why not have joy in /usr/local/bin/

**Comment by swlkr** [comment]
This is actually something that's been bothering me too, I should maybe try to symlink to `/usr/local/bin` or figure out a way to get jpm to put it there

I'll work on this

**Comment by swlkr** [comment]
I attempted to symlink to `/usr/local/bin` at the bottom of `project.janet` so hopefully this happens on install 🤞

**Comment by itsmonktastic** [comment]
FWIW I just did `jpm install joy` today and `joy` is recognized 👍 

```
$ which joy
/usr/local/bin/joy
```

**Comment by hweeks** [comment]
@swlkr can this issue be marked closed?

**Comment by swlkr** [comment]
I usually leave it up to the person who opened the issue to close it, but yeah it can

**Comment by kwccoin** [comment]
Thanks
