### ISSUE TITLE
License needs to be GNU GPL

### ISSUE THREAD

**Issue by staab** [joy-framework/joy#5]
Hey, just thought I'd leave a friendly note that since Circlet is built on Mongoose, which is GNU GPL licensed, MIT isn't an appropriate license for this project. Do leave a comment if you find an MIT-licensed http server in/for Janet, as that is something I'm interested in.

**Comment by swlkr** [comment]
Oh, I never really understood the nuances of GPL vs MIT until you brought it up and I did quick search.

So yeah GPL is no good, I want people to use this in propriety code too without having to open source everything, so I'm going to attempt to switch to [h2o](https://github.com/h2o/h2o)

**Comment by swlkr** [comment]
Not anymore it doesn't! fb2791e115faaec727a19f59d96baf182bd7e1eb
