### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by mbielsk** [joy-framework/joy#53]
Hi,

When running
`jpm install joy `
I get
```
error: No such file or directory: nil\.cache
  in os/mkdir
  in mkdir [E:\Janet-1.9.1\bin\\jpm.janet] on line 145, column 3
  in install-git [E:\Janet-1.9.1\bin\\jpm.janet] on line 687, column 3
  in install-git [E:\Janet-1.9.1\bin\\jpm.janet] on line 678, column 11
  in install [E:\Janet-1.9.1\bin\\jpm.janet] (tailcall) on line 1072, column 20
```

I do have git installed.

**Comment by mbielsk** [comment]
Okay, I figured it out. It wasn't joy related. I had Janet on my PATH, but it turns out that setting JANET_PATH is mandatory. It's strange that installer doesn't do that

**Comment by mbielsk** [comment]
However now I get:

Installed as 'db'.
copying db to E:\Janet-1.9.1/bin...
Invalid switch - /i
Error building git repository dependency: command exited with status 4
From https://github.com/joy-framework/tester
 * branch            master     -> FETCH_HEAD
Already up-to-date.
removing E:\Janet-1.9.1\tester.janet
Error building git repository dependency: No such file or directory: E:\Janet-1.9.1\tester.janet
cloning repository https://github.com/joy-framework/dotenv to E:\Janet-1.9.1\.cache\https___github.com_joy-framework_dotenv
Cloning into 'E:\Janet-1.9.1\.cache\https___github.com_joy-framework_dotenv'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 23 (delta 9), reused 20 (delta 6), pack-reused 0
Unpacking objects: 100% (23/23), done.
Checking connectivity... done.
no dependencies found
generating E:\Janet-1.9.1\.manifests\dotenv.jdn...
Installed as 'dotenv'.
copying dotenv.janet to E:\Janet-1.9.1...
E:dotenv.janet
E:test\dotenv.janet
2 File(s) copied
generating E:\Janet-1.9.1\.manifests\joy.jdn...
Installed as 'joy'.
copying joy to E:\Janet-1.9.1/bin...
Invalid switch - /i
Error building git repository dependency: command exited with status 4

**Comment by swlkr** [comment]
Dang this is one thing I can’t help out with, I don’t have access to windows :(

**Comment by swlkr** [comment]
Oh hey there’s a dockerfile now you’re free to try that out on windows, hopefully it solves the problem 🤞

**Comment by bakpakin** [comment]
This seems to be an issue with `jpm` installation on windows, the `/i` switch is from `jpm` trying to invoke `xcopy` - it seems it is trying to use an older  version of xcopy.  What version of windows are you using?

**Comment by mbielsk** [comment]
Windows 10 Pro

```
help xcopy
Copies files and directory trees.

XCOPY source [destination] [/A | /M] [/D[:date]] [/P] [/S [/E]] [/V] [/W]
                           [/C] [/I] [/Q] [/F] [/L] [/G] [/H] [/R] [/T] [/U]
                           [/K] [/N] [/O] [/X] [/Y] [/-Y] [/Z] [/B] [/J]
                           [/EXCLUDE:file1[+file2][+file3]...]
```

**Comment by bakpakin** [comment]
So I got time to test his out on windows, and it seems xcopy doesn’t handle forward slashes embedded in paths. Added a fix in jpm for this, but there are other issues with installing joy on windows right now - some of them dependent packages don’t work on windows. I would certainly recommend a docker container at this moment.

**Comment by mbielsk** [comment]
Thank you for your time. I belive I should close the issue because according to what you wrote it's no longer issue with joy itself.
