### ISSUE TITLE
Document example broken (and so is defroutes)

### ISSUE THREAD

**Issue by MikeBeller** [joy-framework/joy#61]
The following example from the docs: joy/docs/html-rendering.md doesn't work.  First of all there are several typos / moved parentheses and variables that don't line up.   But more problematic, `defroutes` does not seem to work at all (in any example) when `(import joy)` is used instead of `(use joy)`.

I glanced at the code and it looks like `defroutes` assumes `routes` is defined in the current namespace --which it isn't unless you `(use joy)` (or import it without a prefix). 

I haven't offered a PR for this because I really am just starting to look at joy, and honestly it's quite possible the answer is "you have to `(use joy) instead of import -- only the example is broken, not the code".  

```clojure
(import joy)

(defn home [request])
  [:div "home"]

(joy/defroutes web
  [:get "/" home])

(defn layout [response])
  (let [{:body body} response]
    (joy/respond :html
      (joy/html
       (joy/doctype :html5)
       [:html {:lang "en"}
        [:head
         [:meta {:charset "utf-8"}]
         [:meta {:name "viewport" :content "width=device-width, initial-scale=1"}]
         [:link {:href "/app.css" :rel "stylesheet"}]
         [:title "title"]]
        [:body
         body
         [:script {:src "/app.js"}]]]))))

(def app (-> (joy/handler routes)
             (joy/layout layout)))
```

**Comment by swlkr** [comment]
Ah good catch on those mismatched parens, I kind of didn't use parinfer on some of the docs and just typed them in as markdown without a care in the world haha

As for the defroutes thing, I didn't even realize I had broken this because I always use `(use joy)` or `(import joy :prefix "") but it should work with `(import joy)`.

I'm not sure how to solve this, other than like you said, change the example to this:

```clojure
(import joy)


(defn home [request]
  [:div "home"])


(def routes (joy/routes [:get "/" home]))


(defn layout [response]
  (let [{:body body} response]
    (joy/respond :html
      (joy/html
       (joy/doctype :html5)
       [:html {:lang "en"}
        [:head
         [:meta {:charset "utf-8"}]
         [:meta {:name "viewport" :content "width=device-width, initial-scale=1"}]
         [:link {:href "/app.css" :rel "stylesheet"}]
         [:title "title"]]
        [:body
         body
         [:script {:src "/app.js"}]]]))))


(def app (-> (joy/handler routes)
             (joy/layout layout)))


(joy/server app 9001)
```

**Comment by swlkr** [comment]
You know what, no, I'm just going to stop referencing the routes macro and just duplicate the code in defroutes, since the routes macro has been there and it's been public, so it may be in use. This should work now:

```clojure
(import joy)

(defn home [request]
  [:div "home"])

(joy/defroutes routes
  [:get "/" home])

(defn layout [response]
  (let [{:body body} response]
    (joy/text/html
     (joy/doctype :html5)
     [:html {:lang "en"}
      [:head
       [:meta {:charset "utf-8"}]
       [:meta {:name "viewport" :content "width=device-width, initial-scale=1"}]
       [:link {:href "/app.css" :rel "stylesheet"}]
       [:title "title"]]
      [:body
       body
       [:script {:src "/app.js"}]]])))


(def app (-> (joy/handler routes)
             (joy/layout layout)))

```

**Comment by swlkr** [comment]
5023f6814138dd93dd0c96bd005f30866c5fb36e

**Comment by MikeBeller** [comment]
Thanks @swlkr -- the example code above works fine now.  Appreciate the quick response!
