### ISSUE TITLE
OR's in db/from

### ISSUE THREAD

**Issue by AlecTroemel** [joy-framework/joy#70]
is it possible to do `WHERE ... OR ...` queries in `db/from`? Something like this

```clojure
(db/from :tablename :where {:a a} :or {:b b})
```
(the above doesn't work as far as i can tell)

**Comment by swlkr** [comment]
It's not quite what you were asking but you can do this:

```clojure
(db/from :table :where ["a = ? or b = ?" a b])
```

**Comment by AlecTroemel** [comment]
nice! That does what I need :+1:  thanks for the awesome project!
