### ISSUE TITLE
Invalid CSRF Token

### ISSUE THREAD

**Issue by fancycade** [joy-framework/joy#72]
Hi there!

I'm running into an invalid CSRF token with POST requests when the server is behind an NGINX proxy.

I've tried a number of NGINX configurations but to no avail.

The source code for the app can be found [here](https://git.sr.ht/~fancycade/huddle-janet/tree/master/app.janet).

Thanks!

**Comment by swlkr** [comment]
I’m in the process of making this more explicit but the csrf middleware reads from the ENCRYPTION_KEY environment variable, is that set when running behind nginx?

Hopefully this doc can explain it a little better than what I just did on my phone haha 

https://github.com/joy-framework/joy/blob/master/docs/form-submission.md

**Comment by swlkr** [comment]
You could also rely on samesite=lax or strict and turn off the csrf middleware like this

```clojure
(app {:routes routes :layout layout :csrf-token false})

**Comment by fancycade** [comment]
Thank you very much for the quick reply!

In this case I cloned my repo onto a VM, which didn't track .env, and then made a new file. 

Turns out I was wrong to assume that my app was not using the ENCRYPTION_KEY anywhere :laughing: .

I set it with a key generated from cipher and it is working just fine now.
