### ISSUE TITLE
serve images net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by javan-z** [joy-framework/joy#80]
I'm using the standard created joy template, run joy server
everything works well until I add an image to the page

`[:img {:src "/img/kat.png"}] `

image format doesn't matter tried several

browser console spits out **net::ERR_CONTENT_LENGTH_MISMATCH**

chrome & webkit same result
am I missing something?

**Comment by swlkr** [comment]
Ah, I committed something for a newer version of janet/halo! You aren't missing anything! If you grab the latest from master it'll work since I reverted the problem commit

Fixed with 2d92c4880add69b9dd48ee192b5b9d6619b03a7b

**Comment by javan-z** [comment]
Thank you!
