### ISSUE TITLE
Usability / Docs: joy create migration does not create an empty migration

### ISSUE THREAD

**Issue by LeviSchuck** [joy-framework/joy#87]
While reading the docs https://github.com/joy-framework/joy/blob/master/docs/database-migrations.md , I would have expected 

```
joy create migration
```

to create an empty migration with a default name and have  `-- up` and `-- down` sections

OR

An error message saying a name is needed.

Instead, no file is created and no error is produced.

The correct use would be

```
joy create migration name-here
```

The docs should be updated, and it would be nice if `joy create migration` gave either a generated new migration or an error message.

**Comment by swlkr** [comment]
I changed joy to create a migration with just a timestamp when given no name here: https://github.com/joy-framework/joy/commit/afdf96cf8aa7ff1dd58aa8399d3aadb58207bcb5
