### ISSUE TITLE
performance?

### ISSUE THREAD

**Issue by eko234** [joy-framework/joy#95]
Hi, I'm using joy in production right now for a landing page and some dynamic content, it is a very cool tool, I was using lua with lapis before, which uses open resty and was quite fast, my use case is not speed critical at all and I'm behind a very slow virtual server but I can notice the speed difference, I notice serving static content seems to be what is slower, I wanted to know your thoughts on joy performance/bench marking.

thanks for your work.

**Comment by eko234** [comment]
btw, how are files sent from responses?

**Comment by swlkr** [comment]
hey! thanks for giving joy a shot!

As far as performance goes, my assumption was to only serve static content in development, and in production use nginx or caddy or something.

**Comment by swlkr** [comment]
Also, I’m very open to benchmarking, kind of curious myself, I doubt joy is going to win any speed awards though

**Comment by eko234** [comment]
Oh I see, I was curious about how files are served, for the static middleware I see you basically define a slot with a filepath but couldn't find where or how it is finally delivered, also I know there is work being done for janet libuv bindings, do you think joy would benefit from it?

thanks again!

**Comment by swlkr** [comment]
Ah yes, that’s handled by passing the `:file` key to halo2 https://github.com/joy-framework/halo2/blob/82d4bc5fd97c641fd209668f188d3c485816d52f/src/halo2.janet#L151

**Comment by swlkr** [comment]
And yes, it would definitely benefit from libuv bindings greatly, if there is a better server than halo2 out there, we could switch it!

**Comment by eko234** [comment]
Thanks for the explanation 😊, have a nice day
