### ISSUE TITLE
Issue on a mac and a couple of question

### ISSUE THREAD

**Issue by eclecticlly** [joy-framework/joy#97]
Hi @swlkr, new joy enthusiast here!

I'm on an Intel Macbook Pro 2020.

A couple of thing to note:

- entr is not a standard command on a mac, so you have to install it with brew or joy server doesn't work.
- entr doesn't reload without the -r flag (at least on a mac); I don't have a Linux PC now, so I ask you if it is safe to add it on the standard project.janet template (I will open a PR eventually).

Questions:

- It is possible to use Postgresql instead of Sqlite?
- Do you accept PR to add docs to the website? (after I studied the framework and janet a bit more...)

**Comment by swlkr** [comment]
Hey! Thanks for giving joy a shot!

It is possible to use postgresql! joy uses [joy-framework/db](https://github.com/joy-framework/db) under the hood and the postgres driver is based on the amazing @andrewchambers [janet-pq](https://github.com/andrewchambers/janet-pq) lib

I accept PRs for anything and everything, docs included!

**Comment by swlkr** [comment]
Oh also yeah the `entr` thing, I should add `brew install entr` to the readme, haven't gotten around to it haha

**Comment by eclecticlly** [comment]
Thanks
