### ISSUE TITLE
Joy build failed using (sudo) jpm install

### ISSUE THREAD

**Issue by danvenn** [joy-framework/joy#98]
It's not clear to me what's failing. I get a permission error unless I use sudo.

[joy.log.txt](https://github.com/joy-framework/joy/files/9066067/joy.log.txt)

**Comment by danvenn** [comment]
turns out a fresh Janet install still needs to `jpm install jpm` . Doing so fixed it!

**Comment by danieltanfh95** [comment]
```error: could not open file build/spork/rawterm.meta.janet with mode wb```

Leaving it here for posterity
